name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v30
    - uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
        gc-max-store-size-linux: 1G
    - name: Build nixlet-insecure
      run: nix build .#nixlet-insecure -o nixlet-insecure-unsigned
    - name: Archive nixlet-insecure build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nixlet-insecure-unsigned
        path: nixlet-insecure-unsigned
    - name: Build nixlet
      run: nix build .#nixlet -o nixlet-unsigned
    - name: Archive nixlet build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nixlet-unsigned
        path: nixlet-unsigned
